dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-10-28 12:23:28.936522+00:00
  dag_id: opoadfaq223
  dagrun_timeout: null
  default_args: null
  default_view: null
  deleted_at: null
  description: kpasdf
  doc_md: null
  end_date: null
  fail_stop: false
  full_filepath: null
  id: 151adfiasp09vsd
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: null
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '2025-01-01'
  schedule_interval: hourly
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: null
  template_undefined: ''
  timetable: null
  trigger_url: null
  trigger_url_expected_response: ''
  updated_at: 2024-10-28 12:23:28.936567+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds: 90800
operators:
- created_at: 2024-10-28 12:23:28.220109+00:00
  data:
    sfafd: 1423
  deleted_at: null
  endpoint: https://example.com
  extra_options: null
  headers:
    adfas: afas
  http_conn_id: your_http_connection
  id: 151adfiasp09vsd
  log_response: true
  method: POST
  response_check: null
  task_id: fkakadf
  updated_at: 2024-10-28 12:23:28.220152+00:00
  urls:
  - - https://example.com
  xcom_push: true
