dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-11-04 08:25:15.136991+00:00
  dag_id: testdag1
  dagrun_timeout: null
  default_args: null
  default_view: null
  deleted_at: null
  description: testdesc
  doc_md: null
  end_date: null
  fail_stop: false
  full_filepath: null
  id: -OAqGnIQPeXq3XAuz1gC
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: null
  on_success_callback: null
  orientation: null
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '2025-01-01'
  schedule_interval: hourly
  sla_miss_callback: null
  start_date: null
  tags: null
  template_searchpath: null
  template_undefined: null
  timetable: null
  trigger_url: https://example.com
  trigger_url_expected_response: '{"status": "ok"}'
  updated_at: 2024-11-04 08:25:15.137036+00:00
  user_defined_filters: null
  user_defined_macros: null
  workflow_id: -OAqGnAbY2-0GM_e91l8
data_seconds:
- '1412'
operators:
- connection_id: -OAXZ5H9XRswXPE9-6jE
  created_at: 2024-11-04 08:25:15.928259+00:00
  dag_id: -OAqGnIQPeXq3XAuz1gC
  data: null
  deleted_at: null
  endpoint: https://example.com
  extra_options: null
  headers:
    workl: workl
  http_conn_id: your_http_connection
  id: -OAqGnVMC09AC07SzWvG
  log_response: false
  method: POST
  response_check: null
  task_id: first_endpoint
  updated_at: 2024-11-04 08:25:15.928276+00:00
  urls:
  - - https://example.com
  xcom_push: true
- connection_id: -OAXZ5H9XRswXPE9-6jE
  created_at: 2024-11-04 08:25:16.758180+00:00
  dag_id: -OAqGnIQPeXq3XAuz1gC
  data: null
  deleted_at: null
  endpoint: https://example.com
  extra_options: null
  headers:
    lasdf: cvsfd
  http_conn_id: your_http_connection
  id: -OAqGngGCnVLZhUqNjHV
  log_response: false
  method: POST
  response_check: null
  task_id: second_endpoint
  updated_at: 2024-11-04 08:25:16.758227+00:00
  urls:
  - - https://example.com
  xcom_push: true
