dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-11-05 10:25:47.591368+00:00
  dag_id: testdag9
  dagrun_timeout: null
  default_args: null
  default_view: null
  deleted_at: null
  description: testdesc
  doc_md: null
  end_date: null
  fail_stop: false
  full_filepath: null
  id: -OAvqyns3l7PfeH9e6fc
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: null
  on_success_callback: null
  orientation: null
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '2025-01-01'
  schedule_interval: 0 0 * * *
  sla_miss_callback: null
  start_date: null
  tags: null
  template_searchpath: null
  template_undefined: null
  timetable: null
  trigger_url: https://example.com
  trigger_url_expected_response: '{"status": "ok"}'
  updated_at: 2024-11-05 10:25:47.591388+00:00
  user_defined_filters: null
  user_defined_macros: null
  workflow_id: -OAvqygzvrzQgbQZGAGZ
data_seconds:
- '23'
operators:
- connection_id: -OAXVyYdLLm5cpkAWuCn
  created_at: 2024-11-05 10:25:48.270005+00:00
  dag_id: -OAvqyns3l7PfeH9e6fc
  data:
    foo: bar
  deleted_at: null
  endpoint: https://example.com
  extra_options: null
  headers:
    content-type: application/json
  http_conn_id: your_http_connection
  id: -OAvqyyVUqpzuHSwOtep
  log_response: false
  method: POST
  response_check: null
  task_id: first_endpoint
  updated_at: 2024-11-05 10:25:48.270082+00:00
  urls: null
  xcom_push: true
