dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-11-06 10:31:31.883164+00:00
  dag_id: testdag11
  dagrun_timeout: null
  default_args: null
  default_view: null
  deleted_at: null
  description: testdesc
  doc_md: null
  end_date: null
  fail_stop: false
  full_filepath: null
  id: -OB00s_sKKmz0g9yN38M
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: null
  on_success_callback: null
  orientation: null
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '2025-01-01'
  schedule_interval: 0 0 * * *
  sla_miss_callback: null
  start_date: null
  tags: null
  template_searchpath: null
  template_undefined: null
  timetable: null
  trigger_url: https://example.com
  trigger_url_expected_response: '{"status": "ok"}'
  updated_at: 2024-11-06 10:31:31.883212+00:00
  user_defined_filters: null
  user_defined_macros: null
  workflow_id: -OB00sSibtQilYCDLJlo
data_seconds:
- '12'
operators:
- connection_id: -OAXVyYdLLm5cpkAWuCn
  created_at: 2024-11-06 10:31:33.077259+00:00
  dag_id: -OB00s_sKKmz0g9yN38M
  data:
    number_of_review: 100
  deleted_at: null
  endpoint: /
  endpointurl_id: -OB-izW523IMiOkV8YAX
  extra_options: null
  headers:
    content-type: application/json
  http_conn_id: martin_connection
  id: -OB00srjj6qF9bPmoqhK
  log_response: false
  method: POST
  response_check: null
  task_id: first_endpoint
  updated_at: 2024-11-06 10:31:33.077357+00:00
  urls: null
  xcom_push: true
